parameters:
    planet.controller.class: Planet\PlanetBundle\Controller\PlanetController
    planet.twig_extension.class: Planet\PlanetBundle\Twig\PlanetExtension
    planet.pre_content_view_listener.class: Planet\PlanetBundle\EventListener\PreContentViewListener
    planet.importer.class: Planet\PlanetBundle\Import\Importer
    planet.helper.content.class: Planet\PlanetBundle\Helper\Content

    ezpublish_legacy.view_decorator.twig.class: Planet\PlanetBundle\Legacy\View\TwigContentViewLayoutDecorator

services:
    planet.controller:
        class: %planet.controller.class%
        arguments: [@ezpublish.view_manager, @planet.helper.content]
        calls:
            - [ setContainer, [@service_container] ]

    planet.helper.content:
        class: %planet.helper.content.class%
        arguments: [@ezpublish.api.repository]

    planet:
        alias: planet.controller

    planet.twig_extension:
        class: %planet.twig_extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    planet.pre_content_view_listener:
        class: %planet.pre_content_view_listener.class%
        arguments: [@ezpublish.api.repository, @planet.helper.content]
        tags:
            - {name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView}

    planet.importer:
        class: %planet.importer.class%
        arguments: [@ezpublish.api.repository]

