parameters:
    planet.controller.class: Planet\PlanetBundle\Controller\PlanetController
    planet.twig_extension.class: Planet\PlanetBundle\Twig\PlanetExtension

services:
    planet.controller:
        class: %planet.controller.class%
        calls:
            - [ setContainer, [@service_container] ]

    planet:
        alias: planet.controller

    planet.twig_extension:
        class: %planet.twig_extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
