parameters:
    planet.controller.class: Planet\PlanetBundle\Controller\PlanetController

services:
    planet.controller:
        class: %planet.controller.class%
        calls:
            - [ setContainer, [@service_container] ]

    planet:
        alias: planet.controller
