parameters:
    planet.controller.class: Planet\PlanetBundle\Controller\PlanetController
    planet.twig_extension.class: Planet\PlanetBundle\Twig\PlanetExtension
    planet.pre_content_view_listener.class: Planet\PlanetBundle\EventListener\PreContentViewListener
    planet.importer.class: Planet\PlanetBundle\Import\Importer

    # override the default repository to be able to override
    # the default location service...
    ezpublish.signalslot.repository.class: Planet\PlanetBundle\Repository\Repository

    ezpublish.controller.content.view.class: Planet\PlanetBundle\Controller\ViewController

services:
    planet.controller:
        class: %planet.controller.class%
        arguments: [@ezpublish.view_manager]
        calls:
            - [ setContainer, [@service_container] ]

    planet:
        alias: planet.controller

    planet.twig_extension:
        class: %planet.twig_extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    planet.pre_content_view_listener:
        class: %planet.pre_content_view_listener.class%
        arguments: [@ezpublish.api.repository]
        tags:
            - {name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView}

    planet.importer:
        class: %planet.importer.class%
        arguments: [@ezpublish.api.repository, @ezpublish.config.resolver]

