parameters:
#    planet.example.class: Planet\PlanetBundle\Example

services:
#    planet.example:
#        class: %planet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
