parameters:
    planet.controller.class: Planet\PlanetBundle\Controller\PlanetController
    planet.twig_extension.class: Planet\PlanetBundle\Twig\PlanetExtension
    planet.pre_content_view_listener.class: Planet\PlanetBundle\EventListener\PreContentViewListener

services:
    planet.controller:
        class: %planet.controller.class%
        calls:
            - [ setContainer, [@service_container] ]

    planet:
        alias: planet.controller

    planet.twig_extension:
        class: %planet.twig_extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    planet.pre_content_view_listener:
        class: %planet.pre_content_view_listener.class%
        arguments: [@ezpublish.api.repository]
        tags:
            - {name: kernel.event_listener, event: ezpublish.pre_content_view, method: onPreContentView}
