ezpublish:
    system:
        planete:
            location_view:
                full:
                    planet:
                        template: PlanetBundle:full:planet.html.twig
                        match:
                            Identifier\ContentType: planet
                    post:
                        template: PlanetBundle:full:post.html.twig
                        match:
                            Identifier\ContentType: post
                    site:
                        template: PlanetBundle:full:site.html.twig
                        match:
                            Identifier\ContentType: site
                    page:
                        template: PlanetBundle:full:page.html.twig
                        match:
                            Identifier\ContentType: page
                    folder:
                        template: PlanetBundle:full:folder.html.twig
                        match:
                            Identifier\ContentType: folder
                last_news:
                    site:
                        template: PlanetBundle:last_news:site.html.twig
                        match:
                            Identifier\ContentType: site
                line:
                    post:
                        template: PlanetBundle:line:post.html.twig
                        match:
                            Identifier\ContentType: post
                summary:
                    post:
                        template: PlanetBundle:summary:post.html.twig
                        match:
                            Identifier\ContentType: post
