planet:
    tree:
        root: 2
        blogs: 141
        planetarium: 140
    page:
        posts: 10
        title: "Planète eZ Publish, Ze french corner!"
    import:
        user_id: 14
        type_identifier: 'post'
        mapping:
            # Post property: '<post type field identifier>'
            title: 'title'
            text: 'html'
            url: 'url'
            publishedDate: 'date'
    feed:
        title: "Flux RSS du Planet eZ Publish.fr"
        url_base: "http://www.planet-ezpublish.fr/"
        posts: 20

assetic:
    filters:
        cssrewrite:

parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    locale_fallback: en
    ezpublish_legacy.default.view_default_layout: PlanetBundle::pagelayout.html.twig
