planet:
    tree:
        root: 2
        blogs: 141
        planetarium: 140
    page:
        posts: 10
        title: "Planète eZ Publish, Ze french corner!"

assetic:
    filters:
        cssrewrite:

parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    ezpublish_legacy.view.default_layout: PlanetBundle::pagelayout.html.twig
