planet:
    tree:
        root: 2
        blogs: 141
        planetarium: 140
    page:
        posts: 10
        title: "Planète eZ Publish, Ze french corner!"
    import:
        user_id: 14
        type_identifier: 'post'
        mapping:
            # Post property: '<post type field identifier>'
            title: 'title'
            text: 'html'
            url: 'url'
            publishedDate: 'date'

assetic:
    filters:
        cssrewrite:

parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    ezpublish_legacy.view.default_layout: PlanetBundle::pagelayout.html.twig
